export const DEPARTMENTS = [
  { name: 'All Departments', prefix: '' },
  { name: 'Ancient Studies', prefix: 'ANCS' },
  { name: 'Anthropology', prefix: 'ANTH' },
  { name: 'Applied Linguistics', prefix: 'APLX' },
  { name: 'Applied Mathematics', prefix: 'AM' },
  { name: 'Arabic', prefix: 'ARBC' },
  { name: 'Art', prefix: 'ART' },
  { name: 'Art & Des: Games & Playable Media', prefix: 'ARTG' },
  { name: 'Astronomy and Astrophysics', prefix: 'ASTR' },
  { name: 'Biochemistry and Molecular Bio', prefix: 'BIOC' },
  { name: 'Biology: Molecular Cell & Dev', prefix: 'BIOL' },
  { name: 'Biology: Ecology & Evolutionary', prefix: 'BIOE' },
  { name: 'Biomolecular Engineering', prefix: 'BME' },
  { name: 'Carson College', prefix: 'CRSN' },
  { name: 'Chemistry and Biochemistry', prefix: 'CHEM' },
  { name: 'Chinese', prefix: 'CHIN' },
  { name: 'Coastal Science and Policy', prefix: 'CSP' },
  { name: 'College Nine', prefix: 'CLNI' },
  { name: 'Community Studies', prefix: 'CMMU' },
  { name: 'Computational Media', prefix: 'CMPM' },
  { name: 'Computer Science & Engineering', prefix: 'CSE' },
  { name: 'Cowell College', prefix: 'COWL' },
  { name: 'Creative Technologies', prefix: 'CT' },
  { name: 'Critical Race & Ethnic Studies', prefix: 'CRES' },
  { name: 'Crown College', prefix: 'CRWN' },
  { name: 'Earth Sciences', prefix: 'EART' },
  { name: 'Economics', prefix: 'ECON' },
  { name: 'Education', prefix: 'EDUC' },
  { name: 'Electrical & Computer Engineer', prefix: 'ECE' },
  { name: 'Environmental Sciences', prefix: 'ESCI' },
  { name: 'Environmental Studies', prefix: 'ENVS' },
  { name: 'Feminist Studies', prefix: 'FMST' },
  { name: 'Film and Digital Media', prefix: 'FILM' },
  { name: 'French', prefix: 'FREN' },
  { name: 'Geographic Information Systems', prefix: 'GIST' },
  { name: 'Global and Community Health', prefix: 'GCH' },
  { name: 'Graduate', prefix: 'GRAD' },
  { name: 'Greek', prefix: 'GREE' },
  { name: 'Hebrew', prefix: 'HEBR' },
  { name: 'History', prefix: 'HIS' },
  { name: 'History of Art & Visual Culture', prefix: 'HAVC' },
  { name: 'History of Consciousness', prefix: 'HISC' },
  { name: 'Human Computer Interaction', prefix: 'HCI' },
  { name: 'Humanities', prefix: 'HUMN' },
  { name: 'Italian', prefix: 'ITAL' },
  { name: 'Japanese', prefix: 'JAPN' },
  { name: 'John R. Lewis College', prefix: 'JRLC' },
  { name: 'Kresge College', prefix: 'KRSG' },
  { name: 'Latin', prefix: 'LATN' },
  { name: 'Latin American & Latino Studies', prefix: 'LALS' },
  { name: 'Legal Studies', prefix: 'LGST' },
  { name: 'Linguistics', prefix: 'LING' },
  { name: 'Literature', prefix: 'LIT' },
  { name: 'Materials Sci & Eng', prefix: 'MSE' },
  { name: 'Mathematics', prefix: 'MATH' },
  { name: 'Merrill College', prefix: 'MERR' },
  { name: 'Microbiol & Environ Toxicology', prefix: 'METX' },
  { name: 'Music', prefix: 'MUSC' },
  { name: 'Natural Language Processing', prefix: 'NLP' },
  { name: 'Oakes College', prefix: 'OAKS' },
  { name: 'Ocean Sciences', prefix: 'OCEA' },
  { name: 'Philosophy', prefix: 'PHIL' },
  { name: 'Physical Education', prefix: 'PHYE' },
  { name: 'Physics', prefix: 'PHYS' },
  { name: 'Politics', prefix: 'POLI' },
  { name: 'Porter College', prefix: 'PRTR' },
  { name: 'Psychology', prefix: 'PSYC' },
  { name: 'Science Communication', prefix: 'SCIC' },
  { name: 'Social Documentation', prefix: 'SOCD' },
  { name: 'Sociology', prefix: 'SOCY' },
  { name: 'Spanish', prefix: 'SPAN' },
  { name: 'Spanish for Heritage Speakers', prefix: 'SPHS' },
  { name: 'Statistics', prefix: 'STAT' },
  { name: 'Stevenson College', prefix: 'STEV' },
  { name: 'Technology & Info Management', prefix: 'TIM' },
  { name: 'Theater Arts', prefix: 'THEA' },
  { name: 'UCDC', prefix: 'UCDC' },
  { name: 'Writing', prefix: 'WRIT' },
  { name: 'Yiddish', prefix: 'YIDD' }
];